import Header from "@/components/header"
import Footer from "@/components/footer"
import Back from "@/components/inner/goback"


import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Checkout | Audiophile",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <div className="flex min-h-screen flex-col bg-[#f3f3f2]">
            <div className="bg-[#101010]">
                <Header />
            </div>
            <div className="grow max-w-[1110px] w-full mx-auto pt-[79px] flex flex-col items-start gap-[38px]">
                <Back />
                <div className="bg-white p-12 pt-14 w-full rounded-lg">

                </div>
            </div>

            <Footer />
        </div>
    )
}
